export const styles = {
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #8B6F47 0%, #A0826D 50%, #8B6F47 100%)',
    fontFamily: '"Comic Sans MS", "PingFang SC", "Microsoft YaHei", sans-serif',
    position: 'relative',
    overflow: 'hidden',
  },
  floatingHearts: {
    position: 'fixed',
    width: '100%',
    height: '100%',
    pointerEvents: 'none',
    zIndex: 1,
  },
  heart: {
    position: 'absolute',
    fontSize: '20px',
    opacity: 0.3,
    animation: 'float 15s infinite ease-in-out',
  },
  mainContent: {
    position: 'relative',
    zIndex: 10,
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '20px',
  },
  header: {
    textAlign: 'center',
    padding: '30px 20px',
    background: 'rgba(255, 255, 255, 0.95)',
    borderRadius: '30px',
    boxShadow: '0 10px 40px rgba(0, 0, 0, 0.2)',
    marginBottom: '30px',
  },
  logo: {
    width: '150px',
    height: '90px',
    margin: '0 auto 15px',
    position: 'relative',
  },
  title: {
    fontSize: '2.5em',
    color: '#6B4423',
    margin: '0 0 10px 0',
    textShadow: '2px 2px 4px rgba(0, 0, 0, 0.1)',
  },
  tagline: {
    fontSize: '1.1em',
    color: '#8B6F47',
    fontWeight: 'bold',
    margin: 0,
  },
  card: {
    background: 'rgba(255, 255, 255, 0.95)',
    borderRadius: '25px',
    padding: '40px',
    boxShadow: '0 10px 40px rgba(0, 0, 0, 0.2)',
    marginBottom: '20px',
  },
  formGroup: {
    marginBottom: '25px',
  },
  label: {
    display: 'block',
    color: '#6B4423',
    fontWeight: 'bold',
    marginBottom: '8px',
    fontSize: '1.1em',
  },
  input: {
    width: '100%',
    padding: '15px',
    border: '3px solid #D2691E',
    borderRadius: '15px',
    fontSize: '1em',
    background: '#FFF8DC',
    transition: 'all 0.3s ease',
    boxSizing: 'border-box',
  },
  button: {
    width: '100%',
    padding: '15px',
    background: 'linear-gradient(135deg, #D2691E 0%, #CD853F 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    fontSize: '1.2em',
    fontWeight: 'bold',
    cursor: 'pointer',
    boxShadow: '0 5px 15px rgba(210, 105, 30, 0.4)',
    transition: 'all 0.3s ease',
  },
  chatContainer: {
    height: '500px',
    display: 'flex',
    flexDirection: 'column',
  },
  messagesArea: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px',
    background: '#FFF8DC',
    borderRadius: '20px',
    marginBottom: '20px',
    border: '3px solid #D2691E',
  },
  message: {
    marginBottom: '15px',
    padding: '12px 18px',
    borderRadius: '18px',
    maxWidth: '80%',
    wordWrap: 'break-word',
  },
  userMessage: {
    background: 'linear-gradient(135deg, #D2691E 0%, #CD853F 100%)',
    color: 'white',
    marginLeft: 'auto',
    textAlign: 'right',
  },
  assistantMessage: {
    background: 'white',
    color: '#6B4423',
    border: '2px solid #D2691E',
  },
  inputArea: {
    display: 'flex',
    gap: '10px',
  },
  chatInput: {
    flex: 1,
    padding: '15px',
    border: '3px solid #D2691E',
    borderRadius: '25px',
    fontSize: '1em',
    background: 'white',
  },
  sendButton: {
    padding: '15px 30px',
    background: 'linear-gradient(135deg, #D2691E 0%, #CD853F 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  userInfo: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '15px 20px',
    background: '#FFF8DC',
    borderRadius: '20px',
    marginBottom: '20px',
    border: '3px solid #D2691E',
  },
  logoutButton: {
    padding: '8px 20px',
    background: '#A0826D',
    color: 'white',
    border: 'none',
    borderRadius: '15px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  error: {
    color: '#D2691E',
    background: '#FFF8DC',
    padding: '12px',
    borderRadius: '10px',
    marginBottom: '15px',
    border: '2px solid #D2691E',
  },
};


